### ISSUE TITLE
Welcome View is too big

### ISSUE THREAD

**Issue by alainm23** [alcadica/develop#12]
Thanks for developing this App, when I start the application, the WelcomeView is too big and it occupies all my screen (1366x768) I try to resize but it is not possible, I think it is a big UX problem
![develop](https://user-images.githubusercontent.com/33765137/40368000-4f95b7da-5da0-11e8-8694-6ab80931dac8.png)

**Comment by gh-alcadica** [comment]
Hello @alainm23 ! Thanks for your report!
