### ISSUE TITLE
Use "office-contact" instead of "vcard" icon

### ISSUE THREAD

**Issue by cassidyjames** [alcadica/develop#13]
Not a huge deal, but `office-contact` is the preferred icon name for a vcard-type icon; the `vcard` icon exists as a symlink for backwards compatibility.

https://github.com/alcadica/develop/blob/bf8e81c605e793e46bff6c7481d04bdd8c70efac/src/Views/SettingsView.vala#L35

**Comment by gh-alcadica** [comment]
Thanks for the feedback!
