### ISSUE TITLE
Open Folder on Success

### ISSUE THREAD

**Issue by cassidyjames** [alcadica/develop#14]
**Is your feature request related to a problem? Please describe.**

It's kind of confusing after creating a template project; it's not clear anything happened since it's so fast and I'm taken back to the welcome screen.

**Describe the solution you'd like**

The project folder could open, either in the file manager or in the code editor.

**Describe alternatives you've considered**

I thought about a success dialog or notification or something, but I don't think that's as useful as actually taking me to the files so I can start my work.

**Additional context**

 I'm not sure whether opening a file manager or code editor is better, but whichever is used it should probably use the system default instead of hardcoding any specific app.

**Comment by gh-alcadica** [comment]
At this moment the app will open the directory with the file manager. In future, a treeview will be displayed with capabilities like visual studio (create new classes with the namespace reflecting the dir-tree, adding files to compilation files list and more)
