### ISSUE TITLE
Change requested: Don't create folders in home directory

### ISSUE THREAD

**Issue by cassidyjames** [alcadica/develop#15]
**Describe the bug**

When I create a new project, an empty folder with the project's RDNN name appears in `~/`, which is pretty ugly. I'm not sure what purpose this folder serves, and the app shouldn't treat the user's home directory in that way.

**To Reproduce**
1. Open the app
2. Create a new project of any type
3. Open your home folder in Files
4. See the matching RDNN folder hanging out

**Expected behavior**

Don't create a folder. :) If files have to be kept somewhere, they should be in the folder the user chose for their project, or in a `~/.config/com.github.alcadica.develop/` folder at least.

**Additional context**

I'm going to treat this as a blocker from publishing in AppCenter. Please address it before submitting a new release. If you have any questions or need any clarification, feel free to ask and I'll do my best to help you out. :)

**Comment by gh-alcadica** [comment]
This is a wrong behaviour. The correct one would be to create a rdnn directory inside the directory you choosed. Fixing this soon, thanks for the feedback!
