### ISSUE TITLE
Don't unnecessarily create a custom close button

### ISSUE THREAD

**Issue by danirabbit** [alcadica/develop#17]
https://github.com/alcadica/develop/blob/c6e2f8306368dfb8daf2cba819f43640c3c1c6da/src/Views/Partials/Window/HeaderBar.vala#L28

Instead of doing this, you can just set the property [`show_close_button = true`](https://valadoc.org/gtk+-3.0/Gtk.HeaderBar.show_close_button.html)

**Comment by gh-alcadica** [comment]
Ah, did not know it. Thanks for tip Daniel!
