### ISSUE TITLE
Change the screenshot that only include this app

### ISSUE THREAD

**Issue by ryonakano** [alcadica/develop#18]
According to [this elementary official post](https://medium.com/elementaryos/so-you-wanna-publish-on-appcenter-12c675b56e1c),

> Your screenshot needs to use elementary OS default settings (including window control position), have a transparent background, and should feature your app, not your whole desktop. You can easily take a transparent screenshot using the built in screenshot tool and the “Grab the current window” screenshot mode.

So I think it is better to change the screenshot in README.md to another one that only include this app, IMHO.

**Comment by gh-alcadica** [comment]
Hello @ryonakano, where should I change the screenshot? In the appdata.xml file or in the README.md file?

**Comment by ryonakano** [comment]
Hello.
I think the one in the README.md is better to change `data/screenshots/screenshot-002.png`

**Comment by gh-alcadica** [comment]
Closing, thanks for reporting!
