### ISSUE TITLE
Add build information to README.txt

### ISSUE THREAD

**Issue by RonnyDo** [alcadica/develop#20]
Nice tool, many thanks for that! One idea:
Beginners are probably not very familiar with build systems. It would be nice to instruct them how to compile and run the code.
Maybe a good solution is to generate, depending on the application type, an "Install, build and run" section in the README.md. Actually like you have it in the alcadica/develop project ;-)
For myself I know how to run a compile a normal elementary project. But because it's the first time I created a wingpanel application I have no clue who no run/include the .so (shared library) file...

**Comment by gh-alcadica** [comment]
You are absolutely right. I will work on it soon. About the wingpanel indicator, I will look inside the meson build system, surely it has to be fixes.

**Comment by gh-alcadica** [comment]
Will be released asap! Thanks for your suggestion @RonnyDo!
