### ISSUE TITLE
Default setting shown instead of recently saved ones.

### ISSUE THREAD

**Issue by lewisgoddard** [alcadica/develop#21]
**To Reproduce**
1. Launch for the first time.
2. Enter and save user information
3. Click the settings cog

**Expected behaviour**
Saved user information is displayed

**Current behaviour**
Default user data is displayed.

**Comment by gh-alcadica** [comment]
Thanks for reporting! Will look into it asap!

**Comment by gh-alcadica** [comment]
I cannot reproduce the bug you reported. I've tried to clean install both from github or AppCenter but it seems to work fine, at least for me.  Is Develop installed on Loki or on Juno?

**Comment by lewisgoddard** [comment]
I am using Loki.

**Comment by gh-alcadica** [comment]
This issue will be closed with the 0.10.0 release, thanks for reporting 😊
