### ISSUE TITLE
Add support to another programming languages!

### ISSUE THREAD

**Issue by aimproxy** [alcadica/develop#28]
**Add Support to another languages**
This application is quite good as far as the setup of the project is concerned, but only supports Vala, it would be great if it could support other languages, such as Python, Js, C

**Description**
After choosing "App" in the first menu, another menu could appear where you can choose the language!

**Comment by aimproxy** [comment]
I just picked it up and did this design, I think it's a good start, what do you think?

![Screenshot from 2019-06-21 12 13 18](https://user-images.githubusercontent.com/47716563/59918961-18f2b600-941e-11e9-8405-cf6876d5e36b.png)

How can I start contributing, make a fork, create a branch and then make pull request? You have no contributing.md

**Comment by OctoD** [comment]
It looks really good! Yep, you should branch and then open a pr. my bad I didn’t add a contributing guide, I am sorry

**Comment by aimproxy** [comment]
This project will have to stay for another time, I am very busy with the exams and I have other projects ahead, it will be closed until I have availability again! :/

**Comment by OctoD** [comment]
No problems! Wish you the best with your exams!
