### ISSUE TITLE
Application should inherit from Gtk.Application

### ISSUE THREAD

**Issue by marbetschar** [alcadica/develop#48]
Your App skeleton inherits from `Granite.Application` which I never came across before. After I checked back, the recommended way these days for applications is to inherit from `Gtk.Application`.

Is there a way to communicate the version of the skeletons? I'm aware there are a lot of moving parts and things change over time, so a deviation from official guidelines is inevitable - but right now I don't see a way to easily verify if the generated App skeleton does reflect the latest recommendations.

Which lets me fall back to stick the parts together manually to be safe - even though maybe just a few things changed.

Maybe we can even ask the elementary developers to introduce a version number for the Developer Documentation which you can match your skeleton versions on...?

**Comment by marbetschar** [comment]
Just seen you already fixed this in your source code - but my just installed version from AppCenter does not seem to contain the latest fixes....

**Comment by OctoD** [comment]
Hello @marbetschar, this issue will be closed since a new version is rolling out. Thanks for reporting!
